### ISSUE TITLE
Customize "Reach out with a question"  button link

### ISSUE THREAD

**Issue by bogovicj** [JaneliaSciComp/ossi-website#240]
Specifically, the "Reach out with a question" button on the [BigWarp page](https://janeliascicomp.github.io/ossi-website/projects/bigwarp/) currently links to `mailto:<me>`, where I'd prefer it point to the image.sc forum:
https://forum.image.sc/tag/bigwarp

**Comment by allison-truhlar** [comment]
@bogovicj When I looked into this, I realized I got mixed up with the GitHub issues button and that there already was the ability to customize this link from the `maintainer contact info` field. To make this more memorable/self-explanatory, I changed this field name to `preferred contact method` and added more guidance in the `_project-template.md`about what this field is used for. I also updated the [BigWarp](https://janeliascicomp.github.io/ossi-website/projects/bigwarp/) button link as you requested, so you should be all set!

**Comment by bogovicj** [comment]
Thanks @allison-truhlar !
