### ISSUE TITLE
image from readme not rendering

### ISSUE THREAD

**Issue by alustig3** [JaneliaSciComp/ossi-website#274]
The pipeline diagram in the "GitHub README" tab of the [EASI-FISH page](https://ossi.janelia.org/projects/easi-fish-pipeline/) is not rendering.

<img width="777" alt="image" src="https://github.com/user-attachments/assets/20363c9d-5fcf-43b2-83ae-e69894235e84">

**Comment by allison-truhlar** [comment]
Thanks for raising this issue - it has been addressed by #275. Please check out the [EASI-FISH project page](https://ossi.janelia.org/projects/easi-fish-pipeline/) to confirm.
