### ISSUE TITLE
Some difficulties following the CONTRIBUTING docs

### ISSUE THREAD

**Issue by pattonw** [JaneliaSciComp/ossi-website#305]
What I did:
Fork main branch. run `brew Install node`, `npm install` and `npm run dev`, open "localhost:4321"
On a clean version of the main branch (commit: 0b403d2564bed9f0dc4c75915ec10c8c063c86c0)

In writing this issue I think I found the problems:
1) Trying to navigate to "localhost:4321/ossi-website/projects/cellpose" gives a 404 not found. "localhost:4321/projects/cellpose" works. But the contributing docs mention to navigate to "localhost:4321/ossi-website/projects/<your-project-name>"
2) navigating to "localhost:4321" too quickly results in an error rather than my expected behavior of the website hanging until loaded.

Error Stacktrace:
```
Astro detected an unhandled rejection. Here's the stack trace:
ReferenceError: require is not defined
    at file:///Users/pattonw/Work/Packages/ossi-website/tailwind.config.js:2:22
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:367:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:325:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1396:24)
    at Module._compile (node:internal/modules/cjs/loader:1529:5)
    at Object..js (node:internal/modules/cjs/loader:1678:16)
    at Module.load (node:internal/modules/cjs/loader:1315:32)
    at Function._load (node:internal/modules/cjs/loader:1125:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:216:24)
```

These two issues took me a while to figure out since I'm unfamiliar with most of these tools. I think we need to update the CONTRIBUTING docs to replace all references to "localhost:4321/ossi-website" with "localhost:4321", and maybe make a note that  the server can take some time to start up and will error rather than hang until loaded.

**Comment by allison-truhlar** [comment]
@pattonw Thanks for flagging these issues. I've changed the Contributing docs to replace all references to "localhost:4321/ossi-website" with "localhost:4321", and added a note that navigating to "localhost:4321" before the server starts will result in an error.

The error stacktrace you shared seems to actually be another issue related to how I imported the Tailwind plugin for the CSS - I'm surprised this hasn't come up for others. Could you checkout the `update-readme` [branch](https://github.com/JaneliaSciComp/ossi-website/tree/update-readme) and see if when you run `npm run dev` now whether you get this error? I attempted to address it in this [commit](https://github.com/JaneliaSciComp/ossi-website/commit/915b4a85df86019e7ea6bcce4207f1ec966a8f92).

**Comment by allison-truhlar** [comment]
Thanks for that catch - didn't look in the image when editing the MD file. I've removed all references to `localhost:4321/ossi-website/projects/<your-project-name>` now.

Thanks for confirming the error is fixed!
